/**
 * JSON-LD schema builders — typed helpers for structured data.
 * File path: /lib/schema.ts
 *
 * One file, one source of truth. All brand data flows from
 * /lib/site-config.ts — never hardcoded here.
 *
 * Usage map:
 *   - buildOrganization + buildWebsite → root layout (every page)
 *   - buildLocalBusiness              → home + contact
 *   - buildService + buildFaqPage     → each of the 6 service pages
 *   - buildBreadcrumbs                → all subpages
 *
 * Deliberate omissions (do not add without owner sign-off):
 *   - foundingDate / founder — unknown for the StretchMetal unit
 *   - aggregateRating        — no public reviews exist yet
 *   - priceRange             — quotes are per-drawing, a fake bucket
 *                              would be worse than nothing
 */

import { siteConfig } from "@/lib/site-config";

/* ─── ORGANIZATION ─────────────────────────────────────── */
export function buildOrganization() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": `${siteConfig.url}/#organization`,
    name: siteConfig.name,
    legalName: siteConfig.legalName, // [CONFIRM] legal entity via site-config
    description: siteConfig.description,
    url: siteConfig.url,
    // 180×180 PNG generated by /app/apple-icon.tsx — meets Google's 112px
    // minimum for logo markup; replace with a real logo asset when one exists.
    logo: `${siteConfig.url}/apple-icon`,
    email: siteConfig.contact.email,
    telephone: siteConfig.contact.phone,
    parentOrganization: {
      "@type": "Organization",
      name: siteConfig.parent,
      url: siteConfig.group.belgium.url,
    },
    address: {
      "@type": "PostalAddress",
      streetAddress: siteConfig.contact.address.street,
      addressLocality: siteConfig.contact.address.city,
      postalCode: siteConfig.contact.address.postalCode,
      addressRegion: siteConfig.contact.address.region,
      addressCountry: siteConfig.contact.address.country,
    },
    sameAs: siteConfig.sameAs,
    contactPoint: [
      {
        "@type": "ContactPoint",
        telephone: siteConfig.contact.phone,
        email: siteConfig.contact.email,
        contactType: "sales",
        areaServed: ["PL", "EU"],
        availableLanguage: ["Polish", "English"],
      },
    ],
  };
}

/* ─── WEBSITE ─────────────────────────────────────────── */
export function buildWebsite() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: siteConfig.name,
    url: siteConfig.url,
    inLanguage: ["pl-PL", "en"],
  };
}

/* ─── LOCAL BUSINESS ──────────────────────────────────── */
/**
 * The workshop as a place: address, coordinates, opening hours.
 * Plain LocalBusiness — schema.org has no closer type for a fabrication
 * workshop, and mislabeling (e.g. HomeAndConstructionBusiness) would hurt
 * more than the generic type does.
 */
export function buildLocalBusiness() {
  return {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "@id": `${siteConfig.url}/#localbusiness`,
    name: siteConfig.name,
    description: siteConfig.description,
    image: `${siteConfig.url}${siteConfig.ogImage}`,
    address: {
      "@type": "PostalAddress",
      streetAddress: siteConfig.contact.address.street,
      addressLocality: siteConfig.contact.address.city,
      postalCode: siteConfig.contact.address.postalCode,
      addressRegion: siteConfig.contact.address.region,
      addressCountry: siteConfig.contact.address.country,
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: siteConfig.contact.geo.lat,
      longitude: siteConfig.contact.geo.lng,
    },
    telephone: siteConfig.contact.phone,
    email: siteConfig.contact.email,
    openingHours: siteConfig.contact.hours, // [CONFIRM] via site-config
    sameAs: siteConfig.sameAs,
    parentOrganization: { "@id": `${siteConfig.url}/#organization` },
    url: siteConfig.url,
  };
}

/* ─── SERVICE ─────────────────────────────────────────── */
/**
 * One Service node per service page. `path` is the FULL localized path
 * (e.g. "/uslugi/spawanie" or "/en/services/welding") — pass the output of
 * servicePath()/servicePaths() from /lib/i18n-routes, not a bare slug.
 */
export function buildService(opts: {
  name: string;
  description: string;
  path: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    name: opts.name,
    description: opts.description,
    provider: {
      "@type": "Organization",
      name: siteConfig.name,
      url: siteConfig.url,
    },
    url: `${siteConfig.url}${opts.path}`,
    areaServed: ["PL", "EU"],
  };
}

/* ─── BREADCRUMB LIST ──────────────────────────────────── */
/**
 * Home built as `${siteConfig.url}${routes.home.pl}` yields a trailing
 * slash — normalized to the bare origin so the breadcrumb home item is
 * identical across every page.
 */
export function buildBreadcrumbs(items: { name: string; url: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: item.url === `${siteConfig.url}/` ? siteConfig.url : item.url,
    })),
  };
}

/* ─── FAQ PAGE ─────────────────────────────────────────── */
export function buildFaqPage(faqs: { question: string; answer: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };
}
